### ISSUE TITLE
Not compatible with python 3

### ISSUE THREAD

**Issue by kennes913** [fdellavedova/pycriteo#2]
Since this is a compatibility issue, I didn't fork and follow normal change processes. I modified my local package. 

In order to get mine working, all I did was:

sudo pip install pycriteo --no-dependencies

sudo pip install unicodecsv

And then navigated to installiation and changed **import urllib2** to  **import urllib** in the **clients.py** file.

Seems like the pip issue can be avoided by editing the setup.py file.

**Comment by Tafkas** [comment]
This was solved with #3

**Comment by venturaz87** [comment]
Hi all,

I have an issue with pycriteo. It was working fine, but then I got this error which I am not able to understand. Maybe some of view can help me out on this.


Traceback (most recent call last):
  File "C:/Users/aventurini/PycharmProjects/Lastminute/Criteo/criteo_api_campaigns.py", line 1, in <module>
    from pycriteo import Client
  File "C:\Python27\lib\site-packages\pycriteo\__init__.py", line 42, in <module>
    from .client import Client
  File "C:\Python27\lib\site-packages\pycriteo\client.py", line 29, in <module>
    class Client(object):
  File "C:\Python27\lib\site-packages\pycriteo\client.py", line 50, in Client
    'https://advertising.criteo.com/api/v201010/advertiserservice.asmx?WSDL',
  File "C:\Python27\lib\site-packages\suds\client.py", line 112, in __init__
    self.wsdl = reader.open(url)
  File "C:\Python27\lib\site-packages\suds\reader.py", line 152, in open
    d = self.fn(url, self.options)
  File "C:\Python27\lib\site-packages\suds\wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "C:\Python27\lib\site-packages\suds\reader.py", line 79, in open
    d = self.download(url)
  File "C:\Python27\lib\site-packages\suds\reader.py", line 101, in download
    return sax.parse(string=content)
  File "C:\Python27\lib\site-packages\suds\sax\parser.py", line 136, in parse
    sax.parse(source)
  File "C:\Python27\lib\xml\sax\expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Python27\lib\xml\sax\xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "C:\Python27\lib\xml\sax\expatreader.py", line 217, in feed
    self._err_handler.fatalError(exc)
  File "C:\Python27\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: syntax error


I got the same error if I modified the code to run with the 3.5.

Thanks,
Alessio

**Comment by Tafkas** [comment]
Hi @venturaz87, this issue is fixed with PR #6

**Comment by venturaz87** [comment]
Thanks @Tafkas !
